CREATE TABLE casts (
    id SERIAL PRIMARY KEY,
    actor_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE movies_casts (
    id SERIAL PRIMARY KEY,
    movie_id INT REFERENCES movies(id) ON DELETE CASCADE,
    cast_id INT REFERENCES casts(id) ON DELETE CASCADE,
    character_name VARCHAR(100) NOT NULL
);