name: Build & Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/devbydenis/fgo24-be-tickitz:latest .

      - name: Push Docker Image
        run: docker push ghcr.io/devbydenis/fgo24-be-tickitz:latest

  deploy:
    name: Deploy & Migrate
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Migrations to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "db/migrations"
          target: "/home/denis/deploy"

      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/denis/deploy

            echo "✅ Login GHCR"
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.DENIS_TOKEN }}

            echo "✅ Pull latest images"
            docker compose pull

            echo "✅ Start DB & Redis"
            docker compose up -d db redis

            echo "⏳ Wait for Postgres"
            sleep 10

            echo "✅ Run migrations"
            docker run --rm \
              --network deploy_netapp \
              -v "/home/denis/deploy/migrations:/migrations" \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://postgres:1@db:5432/tikcitz?sslmode=disable" \
              up

            echo "✅ Start App"
            docker compose up -d app

            echo "✅ Deploy Complete"